cursor            {{ colors.primary.dark.hex }}
cursor_text_color {{ colors.on_primary.dark.hex }}

foreground            {{ colors.on_surface.dark.hex }}
background            {{ colors.surface_container_lowest.dark.hex }}
selection_foreground  {{ colors.on_secondary.dark.hex }}
selection_background  {{ colors.secondary.dark.hex }}
url_color             {{ colors.secondary.dark.hex }}

#: black 000000 767676
color0  {{ dank16.color0.default.hex }}
color8  {{ dank16.color8.default.hex }}

#: red cc0403 f2201f
color1  {{ dank16.color1.default.hex }}
color9  {{ dank16.color9.default.hex }}

#: green 19cb00 23fd00
color2  {{ dank16.color2.default.hex }}
color10 {{ dank16.color10.default.hex }}
#: yellow cecb00 fffd00
color3  {{ dank16.color3.default.hex }}
color11 {{ dank16.color11.default.hex }}
#: blue 0d73cc 1a8fff
color4  {{ dank16.color4.default.hex }}
color12 {{ dank16.color12.default.hex }}
#: magenta cb1ed1 fd28ff
color5  {{ dank16.color5.default.hex }}
color13 {{ dank16.color13.default.hex }}
#: cyan 0dcdcd 14ffff
color6  {{ dank16.color6.default.hex }}
color14 {{ dank16.color14.default.hex }}
#: white dddddd ffffff
color7  {{ dank16.color7.default.hex }}
color15 {{ dank16.color15.default.hex }}

mark1_foreground {{ colors.on_primary_fixed.dark.hex }}
mark1_background {{ colors.primary_fixed.dark.hex }}
mark2_foreground {{ colors.on_secondary_fixed.dark.hex }}
mark2_background {{ colors.secondary_fixed.dark.hex }}
mark3_foreground {{ colors.on_tertiary_fixed.dark.hex }}
mark3_background {{ colors.tertiary_fixed.dark.hex }}

active_tab_foreground {{ colors.on_primary.dark.hex }}
active_tab_background {{ colors.primary.dark.hex }}
inactive_tab_foreground {{ colors.on_primary_container.dark.hex }}
inactive_tab_background {{ colors.primary_container.dark.hex }}

active_border_color {{ colors.primary.dark.hex }}
inactive_border_color {{ colors.on_primary.dark.hex }}
# bell_border_color #ff5a00
