-- Generated by Matugen

-- Generated by Matugen
require('base16-colorscheme').setup({
  -- BACKGROUNDS (Keep these as they are or use 'lowest')
  base00 = "{{colors.surface_container_lowest.default.hex}}",
  base01 = "{{colors.surface_container_low.default.hex}}",
  base02 = "{{colors.surface_container.default.hex}}",
  base03 = "{{colors.outline.default.hex}}", -- Better for comments/non-active text
  
  -- FOREGROUNDS
  base04 = "{{colors.on_surface_variant.default.hex}}",
  base05 = "{{colors.on_surface.default.hex}}",
  base06 = "{{colors.on_surface_variant.default.hex | lighten: 10}}",
  base07 = "{{colors.inverse_on_surface.default.hex}}",

  -- SYNTAX (The "Punchy" Colors)
  base08 = "{{colors.error.default.hex}}",           -- Variables/Errors (Red)
  base09 = "{{colors.tertiary.default.hex}}",        -- Constants (Orange/Gold)
  base0A = "{{colors.primary_fixed.default.hex}}",   -- Classes/Types (Vibrant)
  base0B = "{{colors.primary.default.hex}}",         -- Strings (Green/Blue)
  base0C = "{{colors.secondary_fixed.default.hex}}", -- Regex/Escape (Cyan/Teal)
  base0D = "{{colors.secondary.default.hex}}",       -- Functions (Blue/Purple)
  base0E = "{{colors.inverse_primary.default.hex}}", -- Keywords (Strong Highlight)
  base0F = "{{colors.error_container.default.hex | set_saturation: 50.0}}", -- Special/Deprecated
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.on_primary_container.default.hex}}', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '{{colors.tertiary.default.hex | lighten: -15.0 }}',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '{{colors.outline.default.hex}}',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '{{colors.tertiary.default.hex}}',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '{{colors.secondary.default.hex}}',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '{{colors.inverse_primary.default.hex}}',
})
