$terminal = ghostty --gtk-single-instance=true
$fileManager = $terminal -e yazi 
$musicterm = $terminal --class=lofi.player --title="Lofi" -e /home/cuini/.bin/lofi.sh
$menu = rofi -show drun -theme catppuccin
$browser = firefox
$notes = obsidian
