$terminal = kitty --single-instance
$fileManager = $terminal --class=yazi -e yazi 
$musicterm = $terminal --class=lofi.player --title="Lofi" -e /home/cuini/.bin/lofi.sh --instance-group=music
$menu = hyprctl dispatch global quickshell:toggle-run-menu
$browser = firefox
$notes = obsidian
