monitor.alsa.rules = [
    {
      "matches": [
        {
          "node.name": "alsa_output.usb-FIIO_FiiO_K11-01.analog-stereo"
        }
      ],
      "actions": {
        "update-props": {
          "node.description": "FiiO K11",
          "node.nick": "FiiO K11"
        }
      }
    },
    {
      "matches": [
        {
          "node.name": "alsa_input.usb-046d_C922_Pro_Stream_Webcam_B8392E0F-02.analog-stereo"
        }
      ],
      "actions": {
        "update-props": {
          "node.description": "C922 Webcam",
          "node.nick": "C922 Webcam"
        }
      }
    }
  ]

