# Default colors

set -g status-bg                   "#121316"
set -gq @thm_bar_bg                "#121316"

set -gq @thm_bg                    "#1a1b1e"
set -gq @thm_fg                    "#e1e2e6"
set -gq @thm_primary               "#d0bcff"
set -gq @thm_inverse_primary       "#6750a4"
set -gq @thm_surface_low           "#1c1b1f"
set -gq @thm_surface               "#201f23"
set -gq @thm_surface_variant       "#49454f"
set -gq @thm_outline               "#938f99"
set -gq @thm_text_variant          "#cac4d0"

# Apply basic styles immediately
set -g status-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style         "bg=#{@thm_bg},fg=#{@thm_fg}"

# Source matugen
source-file ~/.config/tmux/generated.conf

# Monitor activities in other windows
setw -g monitor-activity on
set -g visual-activity off

# 1. Status Bar General
set -g status-interval 5
set -g status-position bottom
set -g status-style "bg=#{@thm_bar_bg},fg=#{@thm_fg}"

# 2. Left Side - Session Name
# Using a "Pill" look with primary color
set -g status-left-length 100
set -g status-left "#[bg=#{@thm_primary},fg=#{@thm_bg},bold]  #S #[bg=default,fg=#{@thm_primary}] "

# 3. Window List
set -g window-status-separator " "
# Inactive Window
set -g window-status-format "#[fg=#{@thm_text_variant}] #I:#W "
# Active Window
set -g window-status-current-format "#[fg=#{@thm_primary},bg=#{@thm_surface_variant},bold] #[fg=#{@thm_bg},bg=#{@thm_primary}]#I:#W#[fg=#{@thm_primary},bg=#{@thm_surface_variant}]"

# 4. Right Side - Info
set -g status-right-length 100
set -g status-right "#[fg=#{@thm_surface_variant}]#[bg=#{@thm_surface_variant},fg=#{@thm_text_variant}] 󰃭 %Y-%m-%d #[fg=#{@thm_primary},bg=#{@thm_surface_variant}]  %H:%M #[fg=#{@thm_surface_variant},bg=default]"

# 5. Pane Borders (The lines between splits)
set -g pane-border-style "fg=#{@thm_surface_variant}"
set -g pane-active-border-style "fg=#{@thm_primary}"

# 6. Command Prompt / Messages
set -g message-style "bg=#{@thm_primary},fg=#{@thm_bg},bold"


