# Reload tmux config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# new leader
set -g prefix C-s

# mouse support 
set -g mouse on

# vim movements for panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# kitty image protocol
set -g allow-passthrough

set-option -g set-titles on

# Source matugen after setting defaults
source-file ~/.config/tmux/theme.conf

# List plugins for TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
