-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#101417",
  base01 = "#0b0f12",
  base02 = "#181c20",
  base03 = "#41474d",
  base04 = "#c1c7ce",
  base05 = "#e0e3e8",
  base06 = "#2d3135",
  base07 = "#363a3e",

  base08 = "#c2ade1",
  base09 = "#d0c0e8",
  base0A = "#b8c8d9",
  base0B = "#97ccf8",
  base0C = "#4d4162",
  base0D = "#004b71",
  base0E = "#394956",
  base0F = "#97aec7",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#004b71',
  fg = '#cbe6ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#a688d4',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8b9198',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d0c0e8',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b8c8d9',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#29638a',
})
