# Terminal Daemon
exec-once = ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false

# System Services
exec-once = hyprpanel & hyprpaper &
exec-once = systemctl --user start hyprpolkitagent

# Scripts
exec-once = /home/cuini/.config/hypr/randomize-wallpaper.sh "/home/cuini/.config/hypr/wallpapers-everforest" 1

# Clipboard
exec-once = clipse -listen

# Cursor Setup
exec-once = gsettings set org.gnome.desktop.interface cursor-theme BreezeX-RosePine-Linux
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
