$mainMod = SUPER

# System Binds
bind = $mainMod, W, killactive,
bind = $mainMod SHIFT, M, exit,
bind = $mainMod, T, togglefloating,
bind = $mainMod, P, pseudo,
bind = $mainMod SHIFT, T, exec, hyprctl dispatch tagwindow opaque
bind = $mainMod, F, fullscreen,

# Programs
bind = $mainMod, return, exec, $terminal
bind = $mainMod SHIFT, return, exec, $terminal --class="ghostty.float"
bind = $mainMod, E, exec, [float] $fileManager
bind = $mainMod, M, exec, [float] $musicterm
bind = $mainMod, space, exec, $menu
bind = $mainMod, B, exec, $browser

# Navigation (Focus)
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# Window Management (Move/Swap)
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

bind = $mainMod CTRL, H, swapwindow, l
bind = $mainMod CTRL, J, swapwindow, d
bind = $mainMod CTRL, K, swapwindow, u
bind = $mainMod CTRL, L, swapwindow, r

# Workspace Switching
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move Window to Workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Wallpaper Management
bind = $mainMod SHIFT, W, exec, /home/cuini/.config/hypr/randomize-wallpaper.sh "/home/cuini/.config/hypr/wallpapers-everforest"
bind = $mainMod SHIFT, F, exec, /home/cuini/.config/hypr/fetch-wallpaper.sh "https://wallhaven.cc/search?categories=110&purity=100&sorting=random&order=desc&ai_art_filter=1"
bind = $mainMod CTRL ALT, S, exec, /home/cuini/.config/hypr/save-wallpaper.sh
bind = $mainMod SHIFT CTRL ALT, A, exec, /home/cuini/.config/hypr/adapt-wallpaper.sh

# Workspace Scrolling
bind = $mainMod, left, workspace, m-1
bind = $mainMod, right, workspace, m+1

# Mouse Binds
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Media Player Control
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# Screenshots
bind = $mainMod, S, exec, hyprshot -m window --clipboard-only
bind = $mainMod SHIFT, S, exec, hyprshot -m region --clipboard-only
