# --- Colors ---
source = ~/.config/hypr/mocha.conf

# --- Hardware & Layout ---
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/input.conf

# --- Appearance ---
source = ~/.config/hypr/look.conf

# --- Automation ---
source = ~/.config/hypr/programs.conf

source = ~/.config/hypr/autostart.conf

# --- Logic & Interaction ---
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/binds.conf
