source = ~/.config/hypr/modules/colors/colors.conf

source = ~/.config/hypr/modules/hardware/monitors.conf
source = ~/.config/hypr/modules/hardware/input.conf
source = ~/.config/hypr/modules/environment/env.conf

source = ~/.config/hypr/modules/appearance/look.conf

source = ~/.config/hypr/modules/programs/programs.conf
source = ~/.config/hypr/modules/programs/autostart.conf

source = ~/.config/hypr/modules/interaction/rules.conf
source = ~/.config/hypr/modules/interaction/binds.conf

