input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 
    touchpad {
        natural_scroll = false
        tap-to-click = false
        clickfinger_behaviour = 1
    }
}

gesture = 3, horizontal, workspace
gesture = 3, swipe, mod:SUPER, move
gesture = 2, pinch, mod:SUPER, float
gesture = 2, pinch, mod:alt, resize

device {
    name = apple-spi-trackpad
    sensitivity = 0.
    natural_scroll = true
}
