# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = eDP-1,2560x1600,0x0,1.333333

xwayland {
  force_zero_scaling = true
  use_nearest_neighbor = true
  enabled = true
}


# Persistent Workspace Assignments
workspace = 1, monitor:eDP-1, persistent:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:eDP-1, persistent:true
workspace = 5, monitor:eDP-1, persistent:true

