# --- Clipse (Clipboard Manager) ---
windowrule {
    name = clipse
    match:class = ^(clipse)$
    float = on
    size = 622 652
    stay_focused = on
}

# --- Image Viewer ---
windowrule {
    name = mpv-viewer
    match:class = ^(mpv-viewer)$
    float = on
    opaque = on
}

# --- Lofi Player ---
windowrule {
    name = mini-player
    match:class = ^(lofi\.player)$
    float = on
    size = 80 80
    center = on
}

# --- Floating Terminals ---
windowrule {
    name = floating-terminal
    match:class = ^(ghostty\.float)$
    float = on
    center = on
    size = 800 500
}

# --- Opaque ---
windowrule {
    name = opaque
    match:tag = opaque
    opaque = on
}

# --- Global App Fixes ---
windowrule {
    name = global-app-fixes
    match:class = .*
    suppress_event = maximize
}

xwayland {
  force_zero_scaling = true
}


windowrule {
    name = emptym
    match:workspace = emptym
    match:class = ^(sddm-greeter)$
    fullscreen = on
    stay_focused = on
    decorate = off
    no_anim = on
    border_size = 0
    no_dim = on
    rounding = 0
    no_shadow = on
}

# --- Rofi ---

layerrule {
    name = rofi-slide-bottom
    match:namespace = rofi
    animation = slide bottom
}
